### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by DMSledge** [gudenau/minecraft-glitter#2]
java.lang.NoSuchMethodError: 'boolean net.minecraft.class_1799.method_7958()'
	at net.gudenau.minecraft.glitter.common.block.entity.GlitterBlockEntity.push(GlitterBlockEntity.java:82)
	at net.gudenau.minecraft.glitter.common.block.GlitterBlock.method_9534(GlitterBlock.java:59)
	at net.minecraft.class_2680.method_11629(class_2680.java:285)
	at net.minecraft.class_3225.method_14262(class_3225.java:310)
	at net.minecraft.class_3244.method_12046(class_3244.java:922)
	at net.minecraft.class_2885.method_12547(class_2885.java:36)
	at net.minecraft.class_2885.method_11054(class_2885.java:10)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:712)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:706)
	at net.minecraft.class_1255.method_5383(class_1255.java:103)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:690)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:646)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by gudenau** [comment]
I'll have to look into this.

**Comment by gudenau** [comment]
Fixed as of ca6be4cc48f20ed85acb43ba851181bf967af369
